#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  1 00:13:06 2021

@author: root
"""

import matplotlib.pyplot as plt
import numpy as np


def plot_custom(index, values):
  fig, ax = plt.subplots()
  x = np.arange(len(index))
  ax.set_xticks(x)
  ax.set_ylim([0, 110])
  ax.set_xticklabels(index, rotation=75)
  genres_bar = ax.bar(x, values, width=0.45)

  for bar in genres_bar:
    height = bar.get_height()
    ax.annotate('{}'.format(height),
                xy=(bar.get_x() + bar.get_width() / 2, height),
                xytext=(0, 5),
                textcoords="offset points",
                ha='center', va='bottom')
  plt.rcParams.update({'font.size': 26})
  plt.gcf().set_size_inches(16, 8)
  plt.show()



names = ['Iphone 4s', 'Moto Nexus 6', 'Samsung Galaxy S4', 'LG Nexus 5x', 'Samsung Note 3', 'Moto X', 'Moto Droid Maxx', 'HTC One M7', 'Sony Nex 7', 'Iphone 6']
values = [98.64, 94.57, 93.93, 93.02, 95.33, 96.42, 98.15, 98.14, 99.28, 95.25]
plot_custom(names, values)
